### ISSUE TITLE
tilesprite animation ? 

### ISSUE THREAD

**Issue by shohan4556** [nkholski/phaser-animated-tiles#23]
can I use this plugin for tilesprite ?

**Comment by mrsZemiak** [comment]
Hello, 
Did you find the answer? I have the same problem, I really don't know how to use, because the readme doesn't help me. Thank you for your answer

**Comment by shohan4556** [comment]
> Hello, Did you find the answer? I have the same problem, I really don't know how to use, because the readme doesn't help me. Thank you for your answer

yes it works, you have to load, and init the plugin first.
